### ISSUE TITLE
Can you provide what is the structure of your dataset folder?

### ISSUE THREAD

**Issue by foury27** [gabrielkirsten/pseudo_label_keras#1]
I keep getting error like Found 0 images in *** classes..

**Comment by gabrielkirsten** [comment]
I'm sorry @foury27. I'll provide soon.

**Comment by foury27** [comment]
and also, when I ran the main.py  there is the creating symbolic link step.. and I had an error like this"OSError: [Errno 17] File exists"..   Not sure if the symbolic link is necessary? or you need to change your code a little bit to reduce this error?

**Comment by foury27** [comment]
I figured it out. I changed the syslink to copy.  (I have some images of which the names are same in different folders)

**Comment by gabrielkirsten** [comment]
I'm sorry for the delay. The structure of the dataset folder is as follows:
```
./dataset-folder
├── no_label
|	└── no_label
|		└──your_unlabeled_images_here
├── test
|	├──your_class_1_here
|	|	└──your_class_1_images_here
|	└──your_class_n_here
|		└──your_class_n_images_here
├── train
|	├──your_class_1_here
|	|	└──your_class_1_images_here
|	└──your_class_n_here
|		└──your_class_n_images_here
└── validation
	├──your_class_1_here
	|	└──your_class_1_images_here
	└──your_class_n_here
		└──your_class_n_images_here
```

I'll add the structure in the README, thank you for the warning. I'm glad you're trying to use.

**Comment by gabrielkirsten** [comment]
I commit an update to set a random string in the symbolic link on DatasetUtils.py. Maybe this solves your "OSError: [Errno 17] File exists" problem.
![image](https://user-images.githubusercontent.com/15522193/54653657-c3f77a80-4a91-11e9-9a16-1ba13945440c.png)
